name: Reproducible build
on: [pull_request]

jobs:
  jar-artifact-and-hash:
    runs-on: ubuntu-20.04
    container: 
      image: openjdk:8-jdk-slim-buster
    steps:
      - name: Install packages
        run: |
          apt-get update -y && apt-get install -y git curl gnupg
      - name: Checkout code
        uses: actions/checkout@v2
        
