name: Reproducible build
on: [pull_request]

jobs:
  jar-artifact-and-hash:
    runs-on: ubuntu-20.04
    container: 
      image: openjdk@sha256:335627a2118556b3f412287e08ac7febb8ecc46325dc6b3570db56f32d33938f
    steps:
      - name: Install packages
        run: |
          apt-get update -y && apt-get install -y git curl gnupg
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Release key
        run: |
          gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 1A92D8942171AFA951A857365DECF4415E3B8FA4

      - name: Verify files integrity
        run: |
          gpg --verify --output SHA256SUMS SHA256SUMS.asc && sha256sum --check SHA256SUMS

      - name: Build rskj
        run: |
          ./configure.sh && ./gradlew --no-daemon clean build -x test

      - name: Calculate hashes      
        working-directory: rskj-core/build/libs
        run: |
          echo "Pushing hash result to sha256SUMS file."
          ls | grep all.jar | sha256sum ${i} >> SHA256SUMS;
          echo "SHA25SUM hash file content: " 
          cat rskj-core/build/libs/SHA256SUMS

      - name: Export fatjar artifact
        uses: actions/upload-artifact@v2
        with:
          name: rskj-core-${{ github.head_ref }}
          path: rskj-core/build/libs/
          if-no-files-found: error

      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: "Follow this **[link](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})** to access the Github Action execution with the reproducible" });