name: Reproducible build
on: [pull_request]

jobs:
  jar-artifact-and-hash:
    runs-on: ubuntu-20.04
    container: 
      image: openjdk@sha256:335627a2118556b3f412287e08ac7febb8ecc46325dc6b3570db56f32d33938f
    steps:
      - name: Install packages
        run: |
          apt-get update -y && apt-get install -y git curl gnupg
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git checkout HEAD^

      - name: Verify files integrity
        run: |
          gpg --keyserver https://secchannel.rsk.co/release.asc --recv-keys 1A92D8942171AFA951A857365DECF4415E3B8FA4
          gpg --verify --output SHA256SUMS SHA256SUMS.asc && sha256sum --check SHA256SUMS

      - name: Build rskj
        run: |
          ./configure.sh && ./gradlew --no-daemon clean build -x test

      - name: Declare some variables
        id: vars
        working-directory: rskj-core/build/libs
        run: |
          echo ::set-output name=sha256sum::$(cat SHA256SUMS)
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=fatjar_name::$(ls | grep all)" 

      - name: Calculate hashes      
        working-directory: rskj-core/build/libs
        run: |
          echo "Commit: git rev-parse --short HEAD"
          echo "SHA256SUM: `sha256sum $(ls | grep all)`"
